services:
  cf-pangolin:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=XL0qtFXmyloQzdqtPyvkii6clduB21GzqkWStj-n
      - ZONE=diegohernandezdev.com
      - SUBDOMAIN=pangolin
      - PROXIED=false
  cf-immich:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=XL0qtFXmyloQzdqtPyvkii6clduB21GzqkWStj-n
      - ZONE=diegohernandezdev.com
      - SUBDOMAIN=immich
      - PROXIED=false
  cf-stable:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=XL0qtFXmyloQzdqtPyvkii6clduB21GzqkWStj-n
      - ZONE=diegohernandezdev.com
      - SUBDOMAIN=*.stable
      - PROXIED=false
