# To see all available options, please visit the docs:
# https://docs.pangolin.net/

gerbil:
    start_port: 51820
    base_endpoint: "pangolin.diegohernandezdev.com"

app:
    dashboard_url: "https://pangolin.diegohernandezdev.com"
    log_level: "info"
    telemetry:
        anonymous_usage: true

domains:
    domain1:
        base_domain: "diegohernandezdev.com"
        cert_resolver: "letsencrypt" # Or your chosen resolver
        prefer_wildcard_cert: true # This is where you put it

server:
    secret: "w7fuiOnzKbrVuOmd3QpNFUxkezGgpBow"
    cors:
        origins: ["https://pangolin.diegohernandezdev.com"]
        methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
        allowed_headers: ["X-CSRF-Token", "Content-Type"]
        credentials: false
    maxmind_db_path: "./config/GeoLite2-Country.mmdb"

flags:
    require_email_verification: false
    disable_signup_without_invite: true
    disable_user_create_org: false
    allow_raw_resources: true
